const API='https://vertexcraft-api.vertexcrafts1.workers.dev';
const tabs=[...document.querySelectorAll('[data-tab]')];
const panels=[...document.querySelectorAll('[data-panel]')];
const loginModal=document.getElementById('loginModal');
const loginInput=document.getElementById('loginInput');
const loginButton=document.getElementById('loginButton');
const accountButton=document.getElementById('accountButton');
const sideLogin=document.getElementById('sideLogin');
const profileName=document.getElementById('profileName');
const profileHint=document.getElementById('profileHint');
const loginSave=document.getElementById('loginSave');
const buyButtons=[...document.querySelectorAll('.buy-btn[data-url]')];
const fixCss=document.createElement('link');fixCss.rel='stylesheet';fixCss.href='image-fix.css?v=20260905-complete';document.head.append(fixCss);
const hero=document.querySelector('.hero');if(hero){const heroImg=document.createElement('img');heroImg.className='shop-hero-image';heroImg.src='assets/shop-hero-fixed.jpg';heroImg.alt='Minecraft-Portal in der VertexCraft Welt';hero.prepend(heroImg)}
document.querySelectorAll('.product-top').forEach(top=>{const title=top.closest('.product')?.querySelector('h3')?.textContent||'';const img=document.createElement('img');img.className='product-art';if(title.includes('1.000'))img.src='assets/crystals-1000.jpg';else if(title.includes('2.500'))img.src='assets/crystals-2500.jpg';else if(title.includes('5.000'))img.src='assets/crystals-5000.jpg';else if(title.includes('10.000'))img.src='assets/crystals-10000.jpg';else if(title==='Bronze')img.src='assets/rank-bronze.jpg';else if(title==='Gold'||title.startsWith('Gold ·'))img.src='assets/rank-gold.jpg';else if(title==='Diamond')img.src='assets/rank-diamond.jpg';else img.src='assets/shop-battlepass-fixed.jpg';img.alt=title+' Produktbild';top.prepend(img)});
const rankPanel=document.querySelector('[data-panel="ranks"]');if(rankPanel){const comparison=document.createElement('section');comparison.className='rank-comparison';comparison.innerHTML=`<div class="rank-comparison-head"><span class="section-kicker">VORLÄUFIGE VORTEILE</span><h3>Ränge vergleichen</h3><p>Die Vorteile können bis zur endgültigen Veröffentlichung noch angepasst werden.</p></div><div class="rank-table-wrap"><table class="rank-table"><thead><tr><th>Vorteil</th><th class="iron">Iron</th><th class="gold">Gold</th><th class="emerald">Smaragd</th><th class="diamond">Diamant</th></tr></thead><tbody><tr><td>Homes</td><td>8</td><td>12</td><td>16</td><td>20</td></tr><tr><td>Spielzeitgeld-Bonus</td><td>×1.25</td><td>×1.5</td><td>×1.75</td><td>×2.0</td></tr><tr><td>Kein tägliches Limit</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Farbcodes im Chat</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>RGB / Hex-Farben im Chat</td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Fliegen <code>/fly</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Monatlicher VIP-Key</td><td>Icon-Key</td><td>Gold-Key</td><td>Emerald-Key</td><td>Diamond-Key</td></tr><tr class="group"><td colspan="5">Erweiterte Befehle</td></tr><tr><td>Werkbank <code>/craft</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Amboss <code>/anvil</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Endertruhe <code>/enderchest</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Gegenstand als Hut <code>/hat</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Reparieren <code>/repair</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Unendlich essen <code>/feed</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Komprimieren <code>/condense</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr><tr><td>Umbenennen <code>/item rename</code></td><td>✓</td><td>✓</td><td>✓</td><td>✓</td></tr></tbody></table></div>`;rankPanel.append(comparison)}
const rankCss=document.createElement('link');rankCss.rel='stylesheet';rankCss.href='rank-comparison.css?v=20260905';document.head.append(rankCss);
document.querySelectorAll('.rank-table tr').forEach(row=>row.children[3]?.remove());const firstRank=document.querySelector('.rank-table th.iron');if(firstRank){firstRank.textContent='Bronze';firstRank.className='bronze'}document.querySelectorAll('.rank-table .group td').forEach(cell=>cell.colSpan=4);
const checkoutLinks=Object.freeze({
  'https://buy.stripe.com/dRm14f25L1Oy3Eg3LkdMI00':'https://buy.stripe.com/bJe4grbGl3WG5Mo3LkdMI0f',
  'https://buy.stripe.com/5kQfZ9fWBgJs0s4chQdMI01':'https://buy.stripe.com/5kQ00b39P9h01w80z8dMI0g',
  'https://buy.stripe.com/3cI3cnbGl8cW3Eg0z8dMI02':'https://buy.stripe.com/eVqbITbGl3WGeiU0z8dMI0h',
  'https://buy.stripe.com/3cIcMX11Hal4gr281AdMI03':'https://buy.stripe.com/aFa4gr11Hctcgr2fu2dMI0i',
  'https://buy.stripe.com/3cIaEPeSx3WG2Ac5TsdMI09':'https://buy.stripe.com/dRm6ozeSxeBkcaMdlUdMI0c',
  'https://buy.stripe.com/3cI5kvh0F1Oy1w8fu2dMI0a':'https://buy.stripe.com/aFa14f11HeBkgr26XwdMI0d',
  'https://buy.stripe.com/28E28jdOt2SCeiU95EdMI0b':'https://buy.stripe.com/cNi00bdOt2SC8YA4PodMI0e',
  'https://buy.stripe.com/eVqfZ9h0FgJscaM2HgdMI07':'https://buy.stripe.com/bJe00b8u9bp8deQ5TsdMI0j'
});
let player=localStorage.getItem('vertex_player_verified')||'';

const statsLink=document.createElement('a');statsLink.href='https://web.play-vertex.com/stats.html';statsLink.textContent='Ranglisten';document.querySelector('.head-links')?.insertBefore(statsLink,loginButton);
const note=document.querySelector('.login-note');if(note)note.textContent='Dein Spielername wird live mit VertexCraft abgeglichen. Nur Accounts, die bereits mindestens einmal auf dem Server waren, können sich anmelden. Stripe fragt den Namen aktuell zusätzlich im Checkout ab.';

function setTab(name){tabs.forEach(t=>t.classList.toggle('active',t.dataset.tab===name));panels.forEach(p=>p.classList.toggle('active',p.dataset.panel===name));window.scrollTo({top:document.querySelector('.categorybar').offsetTop-80,behavior:'smooth'})}
tabs.forEach(t=>t.addEventListener('click',()=>setTab(t.dataset.tab)));
function validPlayer(name){return /^[A-Za-z0-9_]{1,32}$/.test(name.trim())}
function status(text,ok=false){let el=document.getElementById('loginStatus');if(!el){el=document.createElement('p');el.id='loginStatus';el.className='login-status';loginInput.insertAdjacentElement('afterend',el)}el.textContent=text;el.classList.toggle('verified',ok)}
function openLogin(){loginInput.value=player;status('');loginModal.classList.add('open');setTimeout(()=>loginInput.focus(),50)}
function closeLogin(){loginModal.classList.remove('open')}
function syncLogin(){const logged=validPlayer(player);loginButton.style.display=logged?'none':'inline-block';accountButton.style.display=logged?'inline-block':'none';if(logged){accountButton.textContent='👤 '+player;profileName.textContent=player;profileHint.textContent='Spieler auf VertexCraft bestätigt. Du kannst jetzt einkaufen.';sideLogin.textContent='Spieler wechseln';}else{profileName.textContent='Nicht angemeldet';profileHint.textContent='Nur Spieler, die bereits auf VertexCraft waren, können sich anmelden und einkaufen.';sideLogin.textContent='Jetzt anmelden';}buyButtons.forEach(b=>{b.classList.toggle('locked',!logged);b.textContent=logged?'Kaufen':'🔒 Login';});}
async function verifyPlayer(name){const r=await fetch(`${API}/api/public/exists?name=${encodeURIComponent(name)}`,{headers:{Accept:'application/json'}});if(!r.ok)throw new Error('api_failed');const d=await r.json();return d}
async function doLogin(){const value=loginInput.value.trim();if(!validPlayer(value)){status('Bitte einen gültigen Minecraft-Spielernamen eingeben.');return;}loginSave.disabled=true;loginSave.textContent='Prüfe …';status('Spieler wird auf VertexCraft geprüft …');try{const result=await verifyPlayer(value);if(!result.exists){status('Dieser Spieler war noch nie auf VertexCraft. Ein Shop-Login ist deshalb nicht möglich.');return;}player=result.name||value;localStorage.setItem('vertex_player_verified',player);status('Spieler bestätigt ✓',true);syncLogin();setTimeout(closeLogin,500);}catch(e){status('Die Spielerprüfung ist gerade nicht erreichbar. Prüfe, ob VertexPublicStatsWeb und die öffentliche Worker-Route aktiv sind.');}finally{loginSave.disabled=false;loginSave.textContent='Anmelden';}}
loginButton.addEventListener('click',openLogin);accountButton.addEventListener('click',openLogin);sideLogin.addEventListener('click',openLogin);document.getElementById('loginCancel').addEventListener('click',closeLogin);loginSave.addEventListener('click',doLogin);loginModal.addEventListener('click',e=>{if(e.target===loginModal)closeLogin()});loginInput.addEventListener('keydown',e=>{if(e.key==='Enter')doLogin()});
buyButtons.forEach(btn=>btn.addEventListener('click',e=>{e.preventDefault();if(!validPlayer(player)){openLogin();return;}sessionStorage.setItem('vertex_last_player',player);window.location.href=checkoutLinks[btn.dataset.url]||btn.dataset.url;}));
document.querySelectorAll('[data-copy]').forEach(btn=>btn.addEventListener('click',async()=>{try{await navigator.clipboard.writeText(btn.dataset.copy);const old=btn.textContent;btn.textContent='IP kopiert ✓';setTimeout(()=>btn.textContent=old,1600)}catch{}}));
const params=new URLSearchParams(location.search);if(params.get('payment')==='success'){const box=document.getElementById('successBox');const session=params.get('session_id');box.innerHTML='✓ Zahlung abgeschlossen. Willkommen zurück'+(player?' <strong>'+player+'</strong>':'')+'.'+(session?' Bestell-ID: <code>'+session.slice(0,18)+'…</code>':'');box.classList.add('show');history.replaceState({},'',location.pathname);}
syncLogin();
